general {
    gaps_in = 5
    gaps_out = 10
    border_size = 3

    col.active_border = rgba(a7c080ff)
    col.inactive_border = rgba(425047ff)

    resize_on_border = false
    allow_tearing = false
    layout = dwindle # workspace 1 is master layout
}

misc {
    force_default_wallpaper = 1
    disable_hyprland_logo = false
}
