windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = false
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

workspace = special:magic, layoutopt:orientation:top, layout:scrolling
workspace = 1, layout:master

layerrule = blur on, match:namespace lockscreen
layerrule = animation fade, match:namespace lockscreen

layerrule {
    name=fuzzel

    no_anim=off
    blur=on

    match:namespace=launcher
}