general {
    lock_cmd = pidof hyprlock || hyprlock       # dbus/sysd lock command
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after sleep
}

listener {
    timeout = 500                                # 500 seconds
    on-timeout = loginctl lock-session           # lock screen
}

listener {
    timeout = 530                                # 30s after locking
    on-timeout = hyprctl dispatch dpms off       # turn off displays
    on-resume = hyprctl dispatch dpms on         # turn on displays on activity
}
