source = $HOME/.config/hypr/hyprland/env.conf
source = $HOME/.config/hypr/hyprland/variables.conf
source = $HOME/.config/hypr/hyprland/monitors.conf
source = $HOME/.config/hypr/hyprland/general.conf
source = $HOME/.config/hypr/hyprland/decoration.conf
source = $HOME/.config/hypr/hyprland/layout.conf
source = $HOME/.config/hypr/hyprland/animations.conf
source = $HOME/.config/hypr/hyprland/input.conf
source = $HOME/.config/hypr/hyprland/perms.conf
source = $HOME/.config/hypr/hyprland/rules.conf
source = $HOME/.config/hypr/hyprland/keybinds.conf
source = $HOME/.config/hypr/hyprland/autostart.conf