#     _   ___ _   _         
#    | | / (_) | | |        
#    | |/ / _| |_| |_ _   _ 
#    |    \| | __| __| | | |
#    | |\  \ | |_| |_| |_| |
#    \_| \_/_|\__|\__|\__, |
#                      __/ |
#                     |___/

font_family            JetBrains Mono Nerd Font
bold_font              auto
italic_font            auto
bold_italic_font       auto
font_size              10.0
cursor_shape           block
cursor_shape_unfocused hollow
cursor_blink_interval  0.5 ease-in-out
cursor_trail           1
scrollback_lines       4000
mouse_hide_wait        0
command_on_bell        notify-send "Bell!" "Bell Triggered" --app-name kitty -u normal
allow_remote_control   yes
shell_integration      no-cursor
background_opacity     0.55

##########
# COLORS #
##########

## name: Everforest Dark Medium
## author: Sainnhe

foreground              #d3c6aa
background              #2d353b
selection_foreground    #2d353b
selection_background    #d3c6aa

cursor                  #d3c6aa
cursor_text_color       #2d353b

url_color               #7fbbb3

active_tab_foreground   #2d353b
active_tab_background   #a7c080
inactive_tab_foreground #d3c6aa
inactive_tab_background #3d484d

# Black / Grey
color0 #475258
color8 #9da9a0

# Red
color1 #e67e80
color9 #e67e80

# Green
color2  #a7c080
color10 #a7c080

# Yellow
color3  #dbbc7f
color11 #dbbc7f

# Blue
color4  #7fbbb3
color12 #7fbbb3

# Magenta
color5  #d699b6
color13 #d699b6

# Cyan
color6  #83c092
color14 #83c092

# White / Foreground
color7  #d3c6aa
color15 #d3c6aa
